# ============================== #
#         Application            #
# ============================== #

server:
  port: 8095
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dummy
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
